### ISSUE TITLE
Add Element.

### ISSUE THREAD

**Issue by MohamedElashri** [Robin-Sch/matrix-bridges#1]
This projects seems very good and simple enough for people. I was thinking that this stack should also have element client.

**Comment by Robin-Sch** [comment]
This is meant to be put on a (headless) VPS. It includes a matrix server (synapse) so you would need to open ports if you want to talk to other people (unless you only use it for the bridge).

Other than that it's not that "simple" yet since configuring the bridges requires you to read the docs of those individual bridges (since the installation script isn't done yet), and if you can do that I'm pretty sure you can install element yourself too (or use the web version).

It's good to see someone having interest in this project tho, since afaik I'm the only one using it 😅

I could add a link to download it on the README tho I guess
